name: Deploy whaler to EKS

on:
  push:
    tags: [ "*" ]
    branches:
      - '**'
  pull_request:
    branches: [ "**" ]

env:
  AWS_REGION: us-west-1
  ECR_REPOSITORY: whaler
  K8S_NAMESPACE: whaler

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v2.0
      with:
        version: 'v1.24.0' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::477715925773:role/gh-actions-role
        aws-region: us-east-1
        role-session-name: gh-actions-session

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: whaler
        IMAGE_TAG: 1.1
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    
    - name: Set kubeconfig
      run: |
        mkdir -p $HOME/.kube
        cp $GITHUB_WORKSPACE/kubeconfig.yaml $HOME/.kube/config
            
    - name: Install and configure AWS CLI v2
      run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

    - name: Deploy app to EKS
      env:
        ECR_REGISTRY: ${{ steps.eks-oidc-auth.outputs.aws-region }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        kubectl set image deployment/your-deployment-name your-container-name=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -n $K8S_NAMESPACE
