name: Deploy whaler to EKS

on:
  push:
    tags: [ "*" ]
    branches:
      - '**'
  pull_request:
    branches: [ "**" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.24.0' # default is latest stable
        id: install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::477715925773:role/gh-actions-role
          aws-region: us-east-1

      - name: Fetch Amazon ECR credentials
        id: ecr-login
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ steps.login-ecr.outputs.registry }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update kube config
        id: update-kubeconfig
        run: |
          aws eks update-kubeconfig --name whaler --region us-east-1
          echo "::set-output name=kubeconfig-path::$HOME/.kube/config"

      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          export KUBECONFIG=${{ steps.update-kubeconfig.outputs.kubeconfig-path }}
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
